name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Build Docker image
        run: |
          docker build \
            --build-arg DB_HOST=${DB_HOST} \
            --build-arg DB_PORT=${DB_PORT} \
            --build-arg DB_NAME=${DB_NAME} \
            --build-arg DB_USERNAME=${DB_USERNAME} \
            --build-arg DB_PASSWORD=${DB_PASSWORD} \
            --build-arg GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID} \
            --build-arg GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET} \
            -t your-image-name .
